name: release

on:
  push:
    tags:
      - '*'

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run: go build main.go
      - name: version
        run: echo "::set-output name=version::$(go run main.go version)"
        id: version
      - name: build artifacts
        run: env GOOS=darwin GOARCH=amd64 go build -o oc-quicklab-plugin_$(go run main.go version)_darwin_amd64 github.com/kevydotvinu/oc-quicklab-plugin && env GOOS=linux GOARCH=amd64 go build -o oc-quicklab-plugin_$(go run main.go version)_linux_amd64 github.com/kevydotvinu/oc-quicklab-plugin && env GOOS=windows GOARCH=amd64 go build -o oc-quicklab-plugin_$(go run main.go version)_windows_amd64 github.com/kevydotvinu/oc-quicklab-plugin
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          # body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: oc-quicklab-plugin_${{ steps.version.outputs.version}}_linux_amd64
          asset_name: oc-quicklab-plugin_${{ steps.version.outputs.version}}_linux_amd64
          asset_content_type: application/gzip
      - name: upload darwin artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: oc-quicklab-plugin_${{ steps.version.outputs.version}}_darwin_amd64
          asset_name: oc-quicklab-plugin_${{ steps.version.outputs.version}}_darwin_amd64
          asset_content_type: application/gzip
      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: oc-quicklab-plugin_${{ steps.version.outputs.version}}_windows_amd64
          asset_name: oc-quicklab-plugin_${{ steps.version.outputs.version}}_windows_amd64
          asset_content_type: application/zip
